//! Integration test: walks the permutation corpus generated by
//! `wpawolf-fixturegen permutations` and asserts wpawolf produces the
//! expected `message_pair` byte for every reachable combination.
//!
//! Corpus location: `tests/fixtures/generated/permutations/`.
//! Regenerate with:
//!
//! ```sh
//! cargo run --release -p wpawolf-fixturegen -- permutations --out tests/fixtures/generated/
//! ```

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic,
    clippy::too_many_lines,
    clippy::assigning_clones,
    missing_docs,
    unused_crate_dependencies,
    reason = "integration test module -- strict lints relaxed"
)]

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

const CORPUS_ROOT: &str = "tests/fixtures/generated";
const MANIFEST_PATH: &str = "tests/fixtures/generated/permutations/ground_truth/manifest.toml";

fn binary_path() -> PathBuf {
    let env = std::env::var("CARGO_BIN_EXE_wpawolf");
    if let Ok(p) = env {
        return PathBuf::from(p);
    }
    let target = env!("CARGO_MANIFEST_DIR");
    PathBuf::from(target).join("target").join("release").join("wpawolf")
}

fn unique_suffix() -> u64 {
    static SEQ: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);
    SEQ.fetch_add(1, std::sync::atomic::Ordering::Relaxed)
}

fn run_wpawolf_with_flags(input: &Path, extra_flags: &[&str]) -> String {
    let bin = binary_path();
    let combined =
        std::env::temp_dir().join(format!("wpawolf-perm-{}-{}.combined", std::process::id(), unique_suffix()));
    let _ = fs::remove_file(&combined);
    let mut cmd = Command::new(&bin);
    cmd.arg("-o").arg(&combined);
    for flag in extra_flags {
        cmd.arg(flag);
    }
    cmd.arg(input);
    let status = cmd.status().expect("spawn wpawolf");
    assert!(status.success(), "wpawolf failed on {}", input.display());
    let result = fs::read_to_string(&combined).unwrap_or_default();
    let _ = fs::remove_file(&combined);
    result
}

fn resolve_pcap(entry_path: &str) -> PathBuf {
    PathBuf::from(CORPUS_ROOT).join(
        entry_path.strip_prefix("permutations/").map_or_else(|| entry_path.to_owned(), |p| format!("permutations/{p}")),
    )
}

// --- Manifest parsing ---

struct ManifestEntry {
    path: String,
    mp_byte: u8,
    reachable: bool,
    reference_hash: String,
    cli_flags: Vec<String>,
}

fn parse_manifest() -> Vec<ManifestEntry> {
    let text = fs::read_to_string(MANIFEST_PATH).expect("read permutation manifest");
    let mut entries = Vec::new();
    let mut path = String::new();
    let mut mp_byte: u8 = 0;
    let mut reachable = false;
    let mut reference_hash = String::new();
    let mut cli_flags: Vec<String> = Vec::new();
    let mut in_entry = false;

    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed == "[[permutation]]" {
            if in_entry {
                entries.push(ManifestEntry {
                    path: path.clone(),
                    mp_byte,
                    reachable,
                    reference_hash: reference_hash.clone(),
                    cli_flags: cli_flags.clone(),
                });
            }
            path.clear();
            mp_byte = 0;
            reachable = false;
            reference_hash.clear();
            cli_flags.clear();
            in_entry = true;
            continue;
        }
        if !in_entry {
            continue;
        }
        if let Some(val) = trimmed.strip_prefix("path = \"") {
            path = val.trim_end_matches('"').to_owned();
        } else if let Some(val) = trimmed.strip_prefix("mp_byte = \"") {
            let hex_str = val.trim_end_matches('"').trim_start_matches("0x");
            mp_byte = u8::from_str_radix(hex_str, 16).unwrap_or(0);
        } else if let Some(val) = trimmed.strip_prefix("reachable = ") {
            reachable = val == "true";
        } else if let Some(val) = trimmed.strip_prefix("reference_hash = \"") {
            reference_hash = val.trim_end_matches('"').to_owned();
        } else if let Some(val) = trimmed.strip_prefix("cli_flags = [") {
            let inner = val.trim_end_matches(']');
            cli_flags =
                inner.split(',').map(|s| s.trim().trim_matches('"').to_owned()).filter(|s| !s.is_empty()).collect();
        }
    }
    if in_entry {
        entries.push(ManifestEntry { path, mp_byte, reachable, reference_hash, cli_flags });
    }
    entries
}

// --- Tests ---

#[test]
fn manifest_exists_and_has_150_entries() {
    let entries = parse_manifest();
    assert_eq!(entries.len(), 150, "expected 144 EAPOL + 6 PMKID = 150 permutations");
}

#[test]
fn reachable_eapol_permutations_produce_expected_hash() {
    let entries = parse_manifest();
    let eapol_entries: Vec<&ManifestEntry> =
        entries.iter().filter(|e| e.path.contains("/eapol/") && e.reachable).collect();
    assert!(!eapol_entries.is_empty(), "no reachable EAPOL entries found");

    for entry in &eapol_entries {
        let pcap = resolve_pcap(&entry.path);
        assert!(pcap.exists(), "pcap not found: {}", pcap.display());

        let flags: Vec<&str> = entry.cli_flags.iter().map(String::as_str).collect();
        let output = run_wpawolf_with_flags(&pcap, &flags);
        let lines: Vec<&str> = output.lines().collect();

        let mp_hex = format!("{:02x}", entry.mp_byte);
        let found =
            lines.iter().any(|line| line.ends_with(&format!("*{mp_hex}")) || line.contains(&format!("*{mp_hex}*")));

        assert!(
            found,
            "reachable EAPOL permutation {} (mp=0x{:02x}) not found in wpawolf output.\nExpected reference: {}\nGot {} lines: {:?}",
            entry.path,
            entry.mp_byte,
            &entry.reference_hash[..entry.reference_hash.len().min(80)],
            lines.len(),
            lines
        );
    }
}

#[test]
fn reachable_pmkid_permutations_produce_expected_hash() {
    let entries = parse_manifest();
    let pmkid_entries: Vec<&ManifestEntry> =
        entries.iter().filter(|e| e.path.contains("/pmkid/") && e.reachable).collect();
    assert!(!pmkid_entries.is_empty(), "no reachable PMKID entries found");

    for entry in &pmkid_entries {
        let pcap = resolve_pcap(&entry.path);
        assert!(pcap.exists(), "pcap not found: {}", pcap.display());

        let output = run_wpawolf_with_flags(&pcap, &[]);
        let lines: Vec<&str> = output.lines().collect();

        let mp_hex = format!("{:02x}", entry.mp_byte);
        let mp_pattern = format!("***{mp_hex}");
        let found = lines.iter().any(|line| line.contains(&mp_pattern));

        assert!(
            found,
            "reachable PMKID permutation {} (mp=0x{:02x}) not found in wpawolf output.\nExpected reference: {}\nGot {} lines: {:?}",
            entry.path,
            entry.mp_byte,
            &entry.reference_hash[..entry.reference_hash.len().min(80)],
            lines.len(),
            lines
        );
    }
}

#[test]
fn reachable_reference_hashes_match_wpawolf_output_exactly() {
    let entries = parse_manifest();
    let reachable: Vec<&ManifestEntry> = entries.iter().filter(|e| e.reachable).collect();
    assert!(!reachable.is_empty());

    for entry in &reachable {
        let pcap = resolve_pcap(&entry.path);
        if !pcap.exists() {
            continue;
        }

        let flags: Vec<&str> = entry.cli_flags.iter().map(String::as_str).collect();
        let output = run_wpawolf_with_flags(&pcap, &flags);

        assert!(
            output.lines().any(|line| line == entry.reference_hash),
            "reference hash mismatch for {} (mp=0x{:02x}).\nExpected: {}\nGot:\n{}",
            entry.path,
            entry.mp_byte,
            entry.reference_hash,
            output
        );
    }
}

#[test]
fn every_permutation_pcap_exists() {
    let entries = parse_manifest();
    for entry in &entries {
        let pcap = resolve_pcap(&entry.path);
        assert!(pcap.exists(), "pcap missing: {}", pcap.display());
    }
}

#[test]
fn reference_hashes_file_has_150_lines() {
    let path = PathBuf::from(CORPUS_ROOT).join("permutations/ground_truth/reference_hashes.txt");
    let text = fs::read_to_string(&path).expect("read reference_hashes.txt");
    let non_empty_lines = text.lines().filter(|l| !l.is_empty()).count();
    assert_eq!(non_empty_lines, 150, "expected 150 reference hash lines");
}
